// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGLC-KliqIVKPq21kkwGQ19W8iX8SN83Q',
    appId: '1:864544421142:web:0d9ee9abd406385a3a8c37',
    messagingSenderId: '864544421142',
    projectId: 'studentdetails-27b3d',
    authDomain: 'studentdetails-27b3d.firebaseapp.com',
    storageBucket: 'studentdetails-27b3d.appspot.com',
    measurementId: 'G-GRMDZ3V8JV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWiaE1AmSLzRkUWBxVh2xa9fZRgVv9sTo',
    appId: '1:864544421142:android:77ef48b18ac0e5ce3a8c37',
    messagingSenderId: '864544421142',
    projectId: 'studentdetails-27b3d',
    storageBucket: 'studentdetails-27b3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjsV7SXahcR84taen7uXndp3IdrMxjaJE',
    appId: '1:864544421142:ios:8b71789f26a3365a3a8c37',
    messagingSenderId: '864544421142',
    projectId: 'studentdetails-27b3d',
    storageBucket: 'studentdetails-27b3d.appspot.com',
    iosBundleId: 'com.example.studentDetails',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjsV7SXahcR84taen7uXndp3IdrMxjaJE',
    appId: '1:864544421142:ios:7e1d8762a4f1b32b3a8c37',
    messagingSenderId: '864544421142',
    projectId: 'studentdetails-27b3d',
    storageBucket: 'studentdetails-27b3d.appspot.com',
    iosBundleId: 'com.example.studentDetails.RunnerTests',
  );
}
